function shellScriptPrelude(lines: string[]): string {
  return `${lines.join("\n")}\n`;
}

export function renderZshCompletion(): string {
  return shellScriptPrelude([
    "#compdef run runx",
    "",
    "_run_profiles() {",
    "  local config_path",
    '  config_path="$(command run config path 2>/dev/null)" || return 0',
    "  sed -n 's/^\\[profiles\\.\\([^]]*\\)\\]$/\\1/p' \"$config_path\" 2>/dev/null",
    "}",
    "",
    "_run_managed_names() {",
    "  command run ps 2>/dev/null | awk 'NR > 1 && NF { print $1 }'",
    "}",
    "",
    "_run() {",
    "  emulate -L zsh",
    '  local context curcontext="$curcontext" state ret=1',
    "  typeset -A opt_args",
    "  local -a profiles managed_names",
    '  profiles=(${(f)"$(_run_profiles 2>/dev/null)"})',
    '  managed_names=(${(f)"$(_run_managed_names 2>/dev/null)"})',
    "",
    "  _arguments -C -s -S \\",
    '    "--help[Show help]" \\',
    '    "-h[Show help]" \\',
    '    "--config[Use a specific config file]:config:_files" \\',
    '    "--cwd[Run as if started from this directory]:directory:_files -/" \\',
    '    "--dry-run[Print the resolved command without executing it]" \\',
    '    "--no-cache[Disable metadata cache]" \\',
    '    "--verbose[Show profile, cwd, and config metadata]" \\',
    '    "-v[Show profile, cwd, and config metadata]" \\',
    '    "--details[Show detailed managed-process metrics where supported]" \\',
    '    "--profile[Select a named profile]:profile:(${(j: :)profiles})" \\',
    '    "-p[Select a named profile]:profile:(${(j: :)profiles})" \\',
    '    "1:command:->command" \\',
    '    "*::arg:->args" && ret=0',
    "",
    '  case "$state" in',
    "    command)",
    '      _values "run command" \\',
    '        "init[Create a local .run.toml]" \\',
    '        "completion[Print shell completion scripts]" \\',
    '        "config[View or edit config files]" \\',
    '        "doctor[Inspect project resolution]" \\',
    '        "profiles[List available profiles]" \\',
    '        "up[Start a managed background process]" \\',
    '        "ps[List managed processes]" \\',
    '        "dashboard[Show the managed process overview]" \\',
    '        "inspect[Show detailed process metadata]" \\',
    '        "logs[Show process logs]" \\',
    '        "stop[Stop a managed process]" \\',
    '        "restart[Restart a managed process]" \\',
    '        "kill[Force kill a managed process]" \\',
    '        "ports[Show listening ports for managed processes]" \\',
    '        "help[Show help]" && ret=0',
    "      ;;",
    "    args)",
    "      if (( ${words[(I)--]} )); then",
    "        _files && ret=0",
    "        return ret",
    "      fi",
    '      case "${line[1]}" in',
    "        init)",
    "          _arguments -s -S \\",
    '            "--yes[Skip prompts and accept detected defaults]" \\',
    '            "--force[Overwrite an existing config file]" \\',
    '            "--command[Use a specific default command]:command:_default" \\',
    '            "--default-profile[Choose the profile plain run should execute]:profile:_default" \\',
    '            "--add-profile[Add a named profile]:name=command:_default" && ret=0',
    "          ;;",
    "        completion)",
    '          _values "shell" zsh bash && ret=0',
    "          ;;",
    "        config)",
    "          _arguments -s -S \\",
    '            "1:action:(view path edit validate)" \\',
    '            "--global[Use the global config file]" && ret=0',
    "          ;;",
    "        up)",
    "          _arguments -s -S \\",
    '            "--name[Override the managed process name]:name:_default" \\',
    '            "--profile[Select a named profile]:profile:(${(j: :)profiles})" \\',
    '            "-p[Select a named profile]:profile:(${(j: :)profiles})" \\',
    '            "*::arg:_default" && ret=0',
    "          ;;",
    "        doctor|ports|profiles)",
    '          _arguments -s -S "--json[Print JSON output]" && ret=0',
    "          ;;",
    "        ps)",
    '          _arguments -s -S "--json[Print JSON output]" "--details[Show detailed metrics and ports]" && ret=0',
    "          ;;",
    "        inspect)",
    "          _arguments -s -S \\",
    '            "--json[Print JSON output]" \\',
    '            "1:name or id:(${(j: :)managed_names})" && ret=0',
    "          ;;",
    "        logs)",
    "          _arguments -s -S \\",
    '            "--lines[Show only the last N lines]:count:_default" \\',
    '            "--follow[Follow log output]" \\',
    '            "1:name or id:(${(j: :)managed_names})" && ret=0',
    "          ;;",
    "        stop|restart|kill)",
    '          _arguments -s -S "1:name or id:(${(j: :)managed_names})" && ret=0',
    "          ;;",
    "        *)",
    "          _arguments -s -S \\",
    '            "--profile[Select a named profile]:profile:(${(j: :)profiles})" \\',
    '            "-p[Select a named profile]:profile:(${(j: :)profiles})" \\',
    '            "--verbose[Show profile, cwd, and config metadata]" \\',
    '            "-v[Show profile, cwd, and config metadata]" \\',
    '            "*::arg:_default" && ret=0',
    "          ;;",
    "      esac",
    "      ;;",
    "  esac",
    "",
    "  return ret",
    "}",
    "",
    'if [ "$funcstack[1]" = "_run" ]; then',
    '  _run "$@"',
    "else",
    "  if ! (( $+functions[compdef] )); then",
    "    autoload -Uz compinit",
    '    compinit -i -d "${XDG_CACHE_HOME:-$HOME/.cache}/zsh/.zcompdump-run"',
    "  fi",
    "",
    "  compdef _run run runx",
    "fi",
  ]);
}

export function renderBashCompletion(): string {
  return shellScriptPrelude([
    "_run_profiles() {",
    "  local config_path",
    '  config_path="$(command run config path 2>/dev/null)" || return 0',
    "  sed -n 's/^\\[profiles\\.\\([^]]*\\)\\]$/\\1/p' \"$config_path\" 2>/dev/null",
    "}",
    "",
    "_run_managed_names() {",
    "  command run ps 2>/dev/null | awk 'NR > 1 && NF { print $1 }'",
    "}",
    "",
    "_run_complete() {",
    "  local cur prev cmd profiles managed_names",
    "  COMPREPLY=()",
    '  cur="${COMP_WORDS[COMP_CWORD]}"',
    '  prev="${COMP_WORDS[COMP_CWORD-1]}"',
    '  cmd="${COMP_WORDS[1]}"',
    '  profiles="$(_run_profiles)"',
    '  managed_names="$(_run_managed_names)"',
    '  local commands="init completion config doctor profiles up ps dashboard inspect logs stop restart kill ports help"',
    '  local global_flags="--help -h --config --cwd --dry-run --no-cache --verbose -v --details --profile -p"',
    "",
    "  if [[ ${COMP_CWORD} -eq 1 ]]; then",
    '    COMPREPLY=($(compgen -W "${commands} ${global_flags}" -- "$cur"))',
    "    return 0",
    "  fi",
    "",
    '  if [[ "$prev" == "--profile" || "$prev" == "-p" ]]; then',
    '    COMPREPLY=($(compgen -W "$profiles" -- "$cur"))',
    "    return 0",
    "  fi",
    "",
    '  case "$cmd" in',
    "    init)",
    '      COMPREPLY=($(compgen -W "--yes --force --command --default-profile --add-profile" -- "$cur"))',
    "      ;;",
    "    completion)",
    '      COMPREPLY=($(compgen -W "zsh bash" -- "$cur"))',
    "      ;;",
    "    config)",
    "      if [[ ${COMP_CWORD} -eq 2 ]]; then",
    '        COMPREPLY=($(compgen -W "view path edit validate" -- "$cur"))',
    "      else",
    '        COMPREPLY=($(compgen -W "--global" -- "$cur"))',
    "      fi",
    "      ;;",
    "    doctor)",
    '      COMPREPLY=($(compgen -W "--json" -- "$cur"))',
    "      ;;",
    "    up)",
    '      COMPREPLY=($(compgen -W "--name --profile -p" -- "$cur"))',
    "      ;;",
    "    ps)",
    '      COMPREPLY=($(compgen -W "--json --details" -- "$cur"))',
    "      ;;",
    "    ports|profiles)",
    '      COMPREPLY=($(compgen -W "--json" -- "$cur"))',
    "      ;;",
    "    inspect)",
    "      if [[ ${COMP_CWORD} -eq 2 ]]; then",
    '        COMPREPLY=($(compgen -W "$managed_names" -- "$cur"))',
    "      else",
    '        COMPREPLY=($(compgen -W "--json" -- "$cur"))',
    "      fi",
    "      ;;",
    "    logs)",
    "      if [[ ${COMP_CWORD} -eq 2 ]]; then",
    '        COMPREPLY=($(compgen -W "$managed_names" -- "$cur"))',
    "      else",
    '        COMPREPLY=($(compgen -W "--lines --follow" -- "$cur"))',
    "      fi",
    "      ;;",
    "    stop|restart|kill)",
    '      COMPREPLY=($(compgen -W "$managed_names" -- "$cur"))',
    "      ;;",
    "    *)",
    '      COMPREPLY=($(compgen -W "$global_flags" -- "$cur"))',
    "      ;;",
    "  esac",
    "}",
    "",
    "complete -F _run_complete run runx",
  ]);
}
